name: fox_core
description: "Qui hic minxerit aut cacaverit, habeat deos superos et inferos iratos!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.7
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  equatable: ^2.0.7
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.1
  http: ^1.2.2
  uuid: ^4.5.1
  easy_debounce: ^2.0.3
  flutter_form_builder: ^9.7.0
  basic_utils: ^5.7.0
  package_info_plus: ^8.1.2
  loader_overlay: ^5.0.0
  sign_in_with_apple: ^6.1.4
  get_it: ^8.0.3
  flutter_svg: ^2.0.10+1
  country_code_picker: ^3.1.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_typeahead: ^5.2.0
  flutter_native_splash: ^2.4.4
  form_builder_validators: ^11.1.1
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  transparent_image: ^2.0.1
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: google_fonts/Montserrat-VariableFont_wght.ttf
    - family: Nasalization
      fonts:
        - asset: google_fonts/nasalization-rg.otf

  assets:
    - google_fonts/
    - config/urls.json
    - config/onboarding.json
    - assets/licenses/
    - assets/translations/
    - assets/onboarding/
    - assets/icons/
    - assets/signUp/
    - assets/splash/
    - assets/subscription/
    - assets/placeholder/