"""empty message

Revision ID: 9e87e38171c1
Revises: 1165296c929b
Create Date: 2024-11-15 21:50:37.065846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e87e38171c1'
down_revision = '1165296c929b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcipitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Participation', 'reserve', 'cancelled'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.LargeBinary(length=60),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('parcipitation', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
