"""Remove unique constraint from name, place, and type columns

Revision ID: be5d39413620
Revises: c51d88c55173
Create Date: 2024-11-13 10:49:36.437475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be5d39413620'
down_revision = 'c51d88c55173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('name')
        batch_op.drop_index('place')
        batch_op.drop_index('type')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.LargeBinary(length=60),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('type', ['type'], unique=True)
        batch_op.create_index('place', ['place'], unique=True)
        batch_op.create_index('name', ['name'], unique=True)

    # ### end Alembic commands ###
